alter table PIZZADELIVERY_ORDER alter column EMPLOYER_ID rename to EMPLOYER_ID__U77428 ^
drop index IDX_PIZZADELIVERY_ORDER_ON_EMPLOYER ;
alter table PIZZADELIVERY_ORDER drop constraint FK_PIZZADELIVERY_ORDER_ON_EMPLOYER ;
alter table PIZZADELIVERY_ORDER add column CLERK_EMPLOYER_ID varchar(36) ;
